#!/bin/bash
# 1. Use macro {ALERT.SENDTO} as first parameter (this will be the prowl API key for the user)
# 2. Use macro {ALERT.SUBJECT} as second parameter
# 3. Use macro {ALERT.MESSAGE} as third parameter

/usr/lib/zabbix/alertscripts/prowl.sh "$1" "$2" "$3"